class ScriptInfo:
    SCRIPT_VERSION = 'SCRIPT_VERSION'
    SCRIPT_PACKAGE_NAME = "open+quarter+master-manager-station+captain"
    SCRIPT_TITLE = "Open QuarterMaster Station Captain V${SCRIPT_VERSION}"
    # urls
    HOME_GIT = "https://github.com/Epic-Breakfast-Productions/OpenQuarterMaster"
    STATION_CAPT_GIT = "https://github.com/Epic-Breakfast-Productions/OpenQuarterMaster/tree/main/software/Station%20Captain"
    HOME_PLUGIN_REPO = "https://raw.githubusercontent.com/Epic-Breakfast-Productions/OpenQuarterMaster/main/software/plugins/plugin-repo.json"
    GIT_API_BASE = "https://api.github.com/repos/Epic-Breakfast-Productions/OpenQuarterMaster"
    GIT_RELEASES = "$GIT_API_BASE/releases"
    # files
    TMP_DIR="/tmp/oqm"
    DOWNLOAD_DIR="$TMP_DIR/download"
    DATA_DIR="/data/oqm"
    SHARED_CONFIG_DIR="/etc/oqm"
    META_INFO_DIR="$SHARED_CONFIG_DIR/meta"
    CONFIG_DIR="$SHARED_CONFIG_DIR/config"
    CONFIG_VALUES_DIR="$CONFIG_DIR/configs"
    SERVICE_CONFIG_DIR="$SHARED_CONFIG_DIR/serviceConfig"
    RELEASE_LIST_FILE="$META_INFO_DIR/releases.json"
    RELEASE_LIST_FILE_WORKING="$META_INFO_DIR/releases_unfinished.json"
    RELEASE_LIST_FILE_CUR="$META_INFO_DIR/releases_cur.json"
    RELEASE_VERSIONS_DIR="$META_INFO_DIR/versions"
    RELEASE_INFRA_VERSIONS="$RELEASE_VERSIONS_DIR/infra.json"
    RELEASE_MNGR_VERSIONS="$RELEASE_VERSIONS_DIR/manager.json"
    SNAPSHOT_SCRIPTS_LOC="$SHARED_CONFIG_DIR/snapshot/scripts"