# https://quarkus.io/guides/config-reference
service:
  version: ${quarkus.application.version:0.0.0-TEST} # shouldn't need to default this for testing but here we are. https://github.com/quarkusio/quarkus/issues/15013
  apiVersion: 1.0.0
  nameShort: OQMbase
  nameFull: Open Quarter Master Base Station
  authMode: EXTERNAL # SELF or EXTERNAL
  # Not used if authMode = SELF
  externalAuth:
    name: Keycloak
    url: http://localhost:8080
    realm: realm
    clientId: clientId
    clientSecret: clientSecret
    scope: openid
    interactionBasePath: /auth/realms/${service.externalAuth.realm:}/protocol/openid-connect
    interactionBase: ${service.externalAuth.url:}${service.externalAuth.interactionBasePath:}
#    signInLink: ${service.externalAuth.interactionBase:}/auth?response_type=code&client_id=${service.externalAuth.clientId}&redirect_uri=${service.externalAuth.callbackUrl}&scope=openid&state=TODO&audience=account`
    tokenPath: ${service.externalAuth.interactionBasePath:}/token
    tokenUrl: ${service.externalAuth.url:}${service.externalAuth.tokenPath:}
    callbackUrl: ${runningInfo.baseUrl}/api/user/auth/callback

runningInfo:
  organization: The Testing Organization
  protocol: http
  serverName: ${runningInfo.organization}
  hostname: localhost
  port: ${quarkus.http.port}
  baseUrl: ${runningInfo.protocol}://${runningInfo.hostname}:${runningInfo.port}

quarkus:
  rest-client:
    keycloak:
      url: ${service.externalAuth.url}
      scope: javax.inject.Singleton

    # for demo
    demoService:
      url: http://localhost:8081
      scope: javax.inject.Singleton

  log:
    level: DEBUG
    console:
      format: "%d{HH:mm:ss} [%-5p][%-16X{traceId}|%-2X{parentId}|%-16X{spanId}|%-5X{sampled}][%-40c{2.}](%-26t):: %s%e%n"
  mongodb:
    database: openQuarterMaster
    connection-string: mongodb://localhost:27017
    tracing:
      enabled: true
  #  package:
#    type: uber-jar

  # https://quarkus.io/guides/openapi-swaggerui
  smallrye-openapi:
    info-title: Open QuarterMaster Base Station API
    info-version: ${service.apiVersion}
    info-description: API documentation for the Open QuarterMaster Base Station. Provides all basic functionality. Running on service version ${service.version}
    #    info-terms-of-service: <url>
    info-contact-email: contact@gjstewart.net
    info-contact-name: Greg Stewart
    info-contact-url: https://github.com/Epic-Breakfast-Productions/OpenQuarterMaster
    info-license-name: GNU General Public License v3.0
    info-license-url: https://github.com/Epic-Breakfast-Productions/OpenQuarterMaster/blob/main/LICENSE
    security-scheme: jwt
    security-scheme-name: JwtAuth

  swagger-ui:
    always-include: true
    title: ${quarkus.smallrye-openapi.info-title} v${service.apiVersion}
    theme: flattop
    footer: With <3, EBP
  # https://quarkus.io/guides/opentracing
  jaeger:
    enabled: true
    service-name: ${service.nameShort}v${service.apiVersion}
    sampler-type: const
    sampler-param: 1
#    metrics:
#      enabled: true

mp:
  jwt:
    verify:
      privatekey:
        location: security/packagedPrivateKeyPkcs8.pem
      publickey:
        location: security/packagedPublicKey.pem
      issuer: ${runningInfo.organization} - ${service.nameShort}
    expiration:
      default: 86400 # 1 day
      extended: 2678400 # 1 month
    token:
      header: Cookie
      cookie: jwt

smallrye:
  jwt:
    always-check-authorization: true

"%dev":
  quarkus:
    log:
      level: DEBUG
    smallrye-openapi:
      info-title: Open QuarterMaster Base Station API (DEV)

