package tech.ebp.oqm.core.api.model.object;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;
import org.bson.types.ObjectId;
import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

/**
 * A top level object for use in a Mongodb context.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.ALWAYS)
@SuperBuilder(toBuilder = true)
public abstract class MainObject implements Versionable {
	
	/**
	 * The id of this object in the Mongodb.
	 * <p>
	 * Openapi schema def in `openapi.yaml`
	 */
	@Schema(type = SchemaType.STRING, description = "The Id of this object. Generated by MongoDB if created with null.", defaultValue = "null", readOnly = true)
	private ObjectId id;
}
