apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-oqm-core-depot
  name: {{ .Release.Name }}-oqm-core-depot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-oqm-core-depot
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-oqm-core-depot
    spec:
      containers:
        - image: "docker.io/ebprod/oqm-core-depot:{{ .Values.service.core.depot.imageTag }}"
          name: {{ .Release.Name }}-oqm-core-depot
          resources: {}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
