apiVersion: v1
kind: Service
metadata:
  labels:
    app: oqm-core-depot
  name: oqm-core-depot
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: depot
  selector:
    app: oqm-core-depot
  type: NodePort
