= OQM Station Captain Features
:toc:
:toclevels: 6
:sectnumlevels: 6
:sectanchors:

link:README.md[Back]

== Current
:sectnums:

=== Installing

==== Installers

===== Creation

Installers will be provided for the following operating systems:

 - Debian/ Debian-based via `.deb`

===== Usage

These installers can be used to install the `oqm-captain` management script.

=== Installation Management

==== First time run

If the Open Quarter Base station package is not installed, the script will prompt the user if they want it installed.

If no, continue to the menu.

If so, the Base Station and any supporting infra components will be installed.

==== The Install



==== Uninstallation

=== Configuration Management

==== Config Utility

Alongside the main script is a utility to help get and manage configurations called `oqm-config`. The Features of this are outlined here.

===== List all configs

===== Get individual config values

===== Replace placeholders in file

===== Update values in existing config files

=== Misc

==== Only runs as root

The script needs to run as root to do the administrative tasks it performs. The script will stop execution at the beginning if not root.

:sectnums!:
== Planned
:sectnums:

=== Installing

==== Installers

Installers will be provided for the following operating systems:

- Fedora/ RHEL via `.rpm`



:sectnums!:
== Proposed
:sectnums:


=== Initial setup guide/process

Initial setup process to ask user what type of setup/ business they have, let them select and install plugins that are applicable

:sectnums!:
