= Open Quarter Master Station Captain Guide
:toc:
:toclevels: 5
:sectnums:
:sectnumlevels: 5
:sectanchors:

link:README.md[Back]

More information available on link:https://github.com/Epic-Breakfast-Productions/OpenQuarterMaster/tree/main/software/Station-Captain[GitHub]

== Introduction

This script exists to manage your instance of Open QuarterMaster.

Due to the administrative tasks this script performs, it must be run as root, or with `sudo`.

== Modes

=== Interactive

This is the default mode, run when no arguments are passed. This provides a simple, console-based interface. When running from the system app icon, this is the mode that is run.

To navigate, use `arrow keys`.

To confirm an action, hit `enter`.

To select/deselect an option, press `space`.

You can also navigate by clicking on the menu items you want to select.

==== Flow

When starting up, the script performs a quick check to ensure the core system is installed.
If the core components are not installed, it will prompt you to install them.

==== Menu System

This is a quick explanation of the menus in interactive mode.

(main menu)

. *Info / Status*
.. *Installation Status*
*** Shows how the installed services are running
*** Shows what versions of the software are running (TODO)
.. *Host Information*
*** Shows information about the host, including:
**** IP addresses
**** Hardware information
**** Storage usage
**** RAM usage
. *Manage Installation*

.. *Select OQM major version? TODO*

.. *SSL/HTTPS Certs TODO*
... *Cert mode (self, Let's Encrypt, provided)*
... *Cert info TODO*

.. *Core? TODO*
... *Ensure installed? (TODO)*
... *Common config options (TODO)*

.. *Set Email Settings* +
TODO- document better

*** This menu sets email settings used to send emails from the system
*** These settings are used by various services as well as the system itself
*** Also supports testing these settings

.. *User Administration*
... *Goto keycloak admin console*
... *Toggle self-register* (TODO)
.. *Plugins* TODO
.. *Uninstall All* TODO

. *Snapshots* +
  Snapshots allow you to take a current state of you system, and save it or back it up for later.

.. *Restore from Snapshot* +
   Restores your system to the state from a given snapshot. Will bring down services momentarily while the restore occurs.

.. *Perform snapshot now*
   Performs a snapshot. Will bring down services momentarily while the snapshot occurs.

.. *Enable/disable automatic snapshots*

Enables or disables snapshots from automatically taking place.

.. *Set Snapshot location*
   Sets the location the resulting snapshots are placed.

.. *Set number of snapshots to keep*

Sets the number of snapshots to keep around. This is meant to preserve disk space.

.. *Set automatic snapshot frequency*

Sets how often the automatic snapshots will occur.

. *Cleanup, Maintenance, and Updates*

.. *Updates* TODO

... *Perform Updates (OS and OQM)* TODO

... *Enable/disable automatic updates* TODO

.. *Containers*

... *Prune unused container resources*

... *Enable/disable automatic prune*

... *Set prune frequency*

.. *Data Management*

... *Reset ALL Data*
... *Reset OQM Data* TODO
... *Reset User Data* TODO
... *Reset Plugin Data* TODO

.. *Restart all services*
*** Restarts all services related to OQM
*** Recommended do after config changes and during low usage times.

.. *Restart Device*
*** Does as advertises. Restarts the system that this all runs on.
*** Recommended when weirder issues occur, and after updates.

. *Captain Settings* TODO

=== Python UI (Planned/TODO)

A more user-friendly interface than the standard menu system. Follows the same menu system and layout.

This is a planned feature, so stay tuned.

=== Command

A command line interface is available for performing operations with a single action.

Use `oqm-captain -h` for information in the available options.

== OQM Config

OQM Config is a secondary utility that sits alongside `oqm-captain`, and helps facilitate a smooth operation. Specifically, like it's name implies, it handles the configuration for the system.

More guide to come in the future.

== Other

=== Additional helpful good-to-know

==== Email results of automatic updates


