= Open Quarter Master Station Captain Guide
:toc:
:toclevels: 5
:sectnums:
:sectnumlevels: 5
:sectanchors:

link:README.md[Back]

More information available on link:https://github.com/Epic-Breakfast-Productions/OpenQuarterMaster/tree/main/software/Station-Captain[GitHub]

== Introduction

This script exists to manage your instance of Open QuarterMaster.

Due to the administrative tasks this script performs, it must be run as root, or with `sudo`.

== Modes

=== Interactive

This is the default mode, run when no arguments are passed. This provides a simple, console-based interface. When running from the system app icon, this is the mode that is run.

To navigate, use `arrow keys`.

To confirm an action, hit `enter`.

To select/deselect an option, press `space`.

==== Menu System

This is a quick explanation of the menus in interactive mode.

(main menu)

. Info / Status
.. Installation Status
*** Shows how the installed services are running
*** Shows what versions of the software are running (TODO)
.. Host Information
*** Shows information about the host, including:
**** IP addresses
**** Hardware information
**** Storage usage
**** RAM usage
. Manage Installation TODO
.. Select OQM major version TODO
.. SSL/HTTPS Certs TODO
... Cert mode (self, Let's Encrypt, provided)
... Cert info TODO
.. Core? TODO
... Ensure installed? (TODO)
... Common config options (TODO)
.. Plugins TODO
.. Uninstall All TODO
. Snapshots TODO
.. Restore from Snapshot TODO
.. Enable/disable automatic snapshots TODO
.. Set Snapshot location TODO
.. Set number of snapshots to keep TODO
.. Set automatic snapshot frequency TODO
. Updates TODO
.. Perform Updates (OS and OQM) TODO
.. Enable/disable automatic updates TODO
. Cleanup TODO
.. Docker TODO
... Run cleanup TODO
... Set to do automatically TODO
.. Reset data TODO
. Captain Settings TODO

=== Python UI (Planned/TODO)

A more user-friendly interface than the standard menu system. Follows the same menu system and layout.

This is a planned feature, so stay tuned.

=== Command

A command line interface is available for performing operations with a single action.

Use `oqm-captain -h` for information in the available options.

== Other

=== Additional helpful good-to-know

==== Email results of automatic updates


