#!/usr/bin/env bash
docker run -i \
       -v "$(pwd)/v2jhome/:/tmp/oqm/v2jhome" \
       -v "/dev/shm/:/dev/shm/" \
       -w "/tmp/oqm/v2jhome" \
       -e "HOME=/tmp/oqm/v2jhome" \
       synesthesiam/voice2json "$@"
#       --user "$(id -u):$(id -g)" \
