apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      meta.helm.sh/release-name: mongodb
      meta.helm.sh/release-namespace: quartermaster
    labels:
      app: mongodb
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: mongodb
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: mongodb
      helm.sh/chart: mongodb-10.29.1
      version: v1
    name: mongodb
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/component: mongodb
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/name: mongodb
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          sidecar.istio.io/inject: "true"
        creationTimestamp: null
        labels:
          app: mongodb
          app.kubernetes.io/component: mongodb
          app.kubernetes.io/instance: mongodb
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: mongodb
          helm.sh/chart: mongodb-10.29.1
          version: v1
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: mongodb
                    app.kubernetes.io/instance: mongodb
                    app.kubernetes.io/name: mongodb
                namespaces:
                - quartermaster
                topologyKey: kubernetes.io/hostname
              weight: 1
        containers:
        - env:
          - name: BITNAMI_DEBUG
            value: "false"
          - name: MONGODB_ROOT_USER
            value: root
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mongodb-root-password
                name: mongodb
          - name: ALLOW_EMPTY_PASSWORD
            value: "no"
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
          - name: MONGODB_DISABLE_SYSTEM_LOG
            value: "no"
          - name: MONGODB_DISABLE_JAVASCRIPT
            value: "no"
          - name: MONGODB_ENABLE_JOURNAL
            value: "yes"
          - name: MONGODB_ENABLE_IPV6
            value: "no"
          - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            value: "no"
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - db.adminCommand('ping')
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: mongodb
          ports:
          - containerPort: 27017
            name: mongodb
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data/db
            name: datadir
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: mongodb
        serviceAccountName: mongodb
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: datadir
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: base-station
      app.kubernetes.io/component: open-qm-base-station
      app.kubernetes.io/instance: open-qm-base-station
      deployment: open-qm-base-station
      version: v1
    name: open-qm-base-station
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        deployment: open-qm-base-station
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
          sidecar.istio.io/inject: "true"
        creationTimestamp: null
        labels:
          app: base-station
          deployment: open-qm-base-station
          version: v1
      spec:
        containers:
        - env:
          - name: quarkus.mongodb.connection-string
            value: mongodb://mongodb:27017
          - name: service.authMode
            value: EXTERNAL
          - name: mp.jwt.verify.publickey.location
            value: /tmp/keys/keycloak-public
          - name: mp.jwt.verify.issuer
            value: https://keycloak-sso.apps.sno-demo.nixon.com/auth/realms/apps
          - name: quarkus.oidc.authentication.scopes
            value: profile,address,email,address,phone,offline_access,microprofile-jwt
          - name: quarkus.rest-client.demoService.url
            value: http://demo-plugin:8080
          - name: quarkus.rest-client.demoServiceExternal.url
            value: http://docker-laptop:8080
          - name: runningInfo.baseUrl
            value: https://istio-ingressgateway-istio-system-qm.apps.sno-demo.nixon.com
          - name: service.externalAuth.url
            value: https://keycloak-sso.apps.sno-demo.nixon.com
          - name: service.externalAuth.realm
            value: apps
          - name: service.externalAuth.clientId
            value: quartermaster
          - name: service.externalAuth.clientSecret
            value: bfa4b025-e7d4-4fe0-9eb5-d9a5be644da4
          - name: quarkus.tls.trust-all
            value: "true"
          - name: quarkus.rest-client.demoServiceExternal.readTimeout
            value: "1000"
          - name: runningInfo.hostname
            value: istio-ingressgateway-istio-system-qm.apps.sno-demo.nixon.com
          image: image-registry.openshift-image-registry.svc:5000/quartermaster/open-qm-base-station:0.0.60-native
          imagePullPolicy: IfNotPresent
          name: open-qm-base-station
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          - containerPort: 9779
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp/keys/
            name: keycloak-public
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: quartermaster-base
        serviceAccountName: quartermaster-base
        terminationGracePeriodSeconds: 30
        volumes:
        - name: keycloak-public
          secret:
            defaultMode: 420
            secretName: keycloak-public
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: demo-plugin
      app.kubernetes.io/component: open-qm-plugin-demo
      app.kubernetes.io/instance: open-qm-plugin-demo
      version: v1
    name: open-qm-plugin-demo
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        deployment: open-qm-plugin-demo
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
          sidecar.istio.io/inject: "true"
        creationTimestamp: null
        labels:
          app: demo-plugin
          deployment: open-qm-plugin-demo
          version: v1
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/quartermaster/open-qm-plugin-demo:0.0.60-native
          imagePullPolicy: IfNotPresent
          name: open-qm-plugin-demo
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          - containerPort: 9779
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
