apiVersion: v1
items:
- apiVersion: v1
  data:
    mongodb-root-password: cGFzc3dvcmQxMjM=
  kind: Secret
  metadata:
    name: mongodb
  type: Opaque
- apiVersion: v1
  data:
    keycloak-public: TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFrMzlLZTdubTdwTDZRT25sU0pTc0RJQjJTZXRsVVZGa1RBWmtnSlpOMkdadzFXTldGSWtueDF2QUI3cnVjL04reEZBTWVVWGpSK1hBRG4yYlpWVGlHcmlmeEdHRXphMk5CazZOTmVIR2JpWE1UdFoxckZhYThZVnBLZ1FySE5yb3RPdkZzMGErU2pRd2RWRDFBU0VzY0xVdFhiS0xzSjR1YXJxYUkyN3BmTThENGZCS2RzQmdZTllUdmFTQmRJWXlLeHFKZUFHZ1A2MktNNTl3YS9yNmQ0SGFyMHdMbkZKRGtFRER5ZXc3WnJONE5odHlBODh2Q1IxQ29ZeVlhWmNqNURnNi9nZERTRUtMeXZnUVRhaDlKV1lTVmNxSXM4THdMbm9xeTRKV1dzbWVsQ0piZ2tRL3g3a0RieWQ0MGwrc1AyaUNjN2ZIVWRjdWVzSGRTb1R1aXdJREFRQUI=
  kind: Secret
  metadata:
    name: keycloak-public
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

