apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-oqm-core-depot-ingress
spec:
  rules:
    - host: {{ .Release.Name }}-oqm-core-depot # the hostname to respond to (possibly include whole domain name of stack + servcice name)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-oqm-core-depot
                port:
                  number: 80