name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - gregjstewart
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: dropdown
    id: softwareComponent
    attributes:
      label: Software
      description: What component(s) are part of the bug?
      multiple: true
      required: true
      options:
        - Base Station
        - Station Captain
        - Infra - Mongo
        - Plugins- *
        
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
      
  - type: textarea
    id: env
    attributes:
      label: In what context(s) are you seeing this issue?
      description: What OS(s) are you using? What Browser(s)? Any other useful context surrounding how you are using the software?
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. Reminder to not include sensitive information.
      render: shell
