blank_issues_enabled: true
contact_links:
  - name: Open QuarterMaster Discussions
    url: https://github.com/Epic-Breakfast-Productions/OpenQuarterMaster/discussions
    about: Chat hangout for all things OpenQuarterMaster. You can try asking your questions there first!
