import { describe,it,expect,vi } from 'vitest';
import { DEFAULT_SETTINGS, productKey, purchaseAttribute, sourceAttribute, type InventoryItem, type Purchase } from '../src/domain';
import { ApiError, OqmClient } from '../src/oqm/client';
import { createPayload, ledgerRecord, setDeliveryStatus, syncLine } from '../src/oqm/sync';
const ID='6aa1b7b7f999a6abc5d1de95';
function order():Purchase { return {key:'amazon:amazon.com:123-1234567-1234567',orderId:'123-1234567-1234567',sourceUrl:'https://www.amazon.com/gp/buy/thankyou/',capturedAt:'2026-09-14T00:00:00Z',target:{...DEFAULT_SETTINGS},lines:[{product:{source:'amazon',marketplace:'amazon.com',productId:'B012345678',title:'Battery 12 pack',quantity:2,url:'https://www.amazon.com/dp/B012345678'},phase:'pending',choice:'new'}],warnings:[],approved:true,status:'queued',attempts:0}; }
function fakeApi() {
  const db=new Map<string,InventoryItem>();let creations=0,patches=0;
  const api={
    byAttribute:vi.fn(async(k:string)=>[...db.values()].filter(i=>k in i.attributes)),
    findSource:vi.fn(async(p:Purchase['lines'][0]['product'])=>[...db.values()].filter(i=>sourceAttribute(p) in i.attributes)),
    getItem:vi.fn(async(id:string)=>{const i=db.get(id);if(!i)throw new Error('Not found');return structuredClone(i);}),
    createItem:vi.fn(async(body:Record<string,unknown>)=>{creations++;const i={...body,id:ID} as unknown as InventoryItem;db.set(ID,structuredClone(i));return structuredClone(i);}),
    patchItem:vi.fn(async(id:string,body:Partial<InventoryItem>)=>{patches++;const i={...db.get(id)!,...body};db.set(id,structuredClone(i));return structuredClone(i);}),
  };return {api:api as unknown as OqmClient,mock:api,db,counts:()=>({creations,patches})};
}
describe('purchase synchronization',()=>{
  it('creates a product with incoming metadata, links and no physical stock',async()=>{const p=order(),f=fakeApi();await syncLine(f.api,p,p.lines[0],async()=>{});expect(p.lines[0].phase).toBe('done');const item=f.db.get(ID)!;const record=JSON.parse(item.attributes[await purchaseAttribute(p,p.lines[0].product)]);expect(record).toMatchObject({status:'incoming',quantityPurchased:2,inventoryQuantity:2});expect(item.associatedLinks?.[0].link).toContain('/dp/');expect(f.counts().creations).toBe(1);expect(f.mock.getItem).toHaveBeenCalled();});
  it('replaying the same order across a fresh local state does not create again',async()=>{const f=fakeApi(),p=order();await syncLine(f.api,p,p.lines[0],async()=>{});const replay=order();await syncLine(f.api,replay,replay.lines[0],async()=>{});expect(f.counts()).toEqual({creations:1,patches:0});expect(replay.lines[0].phase).toBe('done');});
  it('records a repeat purchase on the same product',async()=>{const f=fakeApi(),p=order();await syncLine(f.api,p,p.lines[0],async()=>{});const next=order();next.orderId='222-2222222-2222222';next.key='amazon:amazon.com:'+next.orderId;await syncLine(f.api,next,next.lines[0],async()=>{});expect(f.counts()).toEqual({creations:1,patches:1});expect(Object.keys(f.db.get(ID)!.attributes).filter(k=>k.startsWith('oqmCart_purchase_'))).toHaveLength(2);});
  it('preserves unrelated metadata and converts purchased packs into mapped units',async()=>{const p=order(),f=fakeApi();f.db.set(ID,{id:ID,name:'AA Battery',unit:{string:'units'},attributes:{owner:'science'},keywords:['lab'],associatedLinks:[{label:'vendor',link:'https://example.com'}]});p.lines[0].mapping={productKey:productKey(p.lines[0].product),itemId:ID,itemName:'AA Battery',multiplier:12,unit:'units'};await syncLine(f.api,p,p.lines[0],async()=>{});const i=f.db.get(ID)!;expect(i.attributes.owner).toBe('science');expect(i.keywords).toContain('lab');expect(i.associatedLinks).toHaveLength(2);expect(JSON.parse(i.attributes[await purchaseAttribute(p,p.lines[0].product)]).inventoryQuantity).toBe(24);});
  it('will not synchronize an unapproved purchase',async()=>{const p=order(),f=fakeApi();p.approved=false;await expect(syncLine(f.api,p,p.lines[0],async()=>{})).rejects.toThrow('review');expect(f.counts().creations).toBe(0);});
  it('will not assume a missing purchased quantity',async()=>{const p=order(),f=fakeApi();p.lines[0].product.quantity=null;await expect(syncLine(f.api,p,p.lines[0],async()=>{})).rejects.toThrow();});
  it('journals before POST and reconciles a lost response',async()=>{const p=order(),f=fakeApi();const original=f.mock.createItem.getMockImplementation()!;f.mock.createItem.mockImplementationOnce(async b=>{await original(b);throw new ApiError('Lost response',0,true);});const persist=vi.fn(async()=>{});await expect(syncLine(f.api,p,p.lines[0],persist)).rejects.toThrow();expect(p.lines[0].phase).toBe('creating');expect(persist).toHaveBeenCalled();await syncLine(f.api,p,p.lines[0],persist);expect(f.counts().creations).toBe(1);expect(p.lines[0].phase).toBe('done');});
  it('does not retry an uncertain create that cannot be reconciled',async()=>{const p=order(),f=fakeApi();p.lines[0].phase='creating';await expect(syncLine(f.api,p,p.lines[0],async()=>{})).rejects.toThrow('previous creation');expect(f.counts().creations).toBe(0);});
  it('allows retry after a definite validation rejection',async()=>{const p=order(),f=fakeApi();f.mock.createItem.mockRejectedValueOnce(new ApiError('Bad request',400,false));await expect(syncLine(f.api,p,p.lines[0],async()=>{})).rejects.toThrow();expect(p.lines[0].phase).toBe('pending');});
  it('does not duplicate a purchase with changed quantities',async()=>{const p=order(),f=fakeApi();await syncLine(f.api,p,p.lines[0],async()=>{});const changed=order();changed.lines[0].product.quantity=5;await expect(syncLine(f.api,changed,changed.lines[0],async()=>{})).rejects.toThrow('different quantities');expect(f.counts().creations).toBe(1);});
  it('rejects a changed target unit before patching',async()=>{const p=order(),f=fakeApi();f.db.set(ID,{id:ID,name:'Battery',unit:{string:'kg'},attributes:{}});p.lines[0].mapping={productKey:productKey(p.lines[0].product),itemId:ID,itemName:'Battery',multiplier:1,unit:'units'};await expect(syncLine(f.api,p,p.lines[0],async()=>{})).rejects.toThrow('unit changed');expect(f.counts().patches).toBe(0);});
  it('changes delivery metadata and removes incoming tag when no incoming purchases remain',async()=>{const p=order(),f=fakeApi();await syncLine(f.api,p,p.lines[0],async()=>{});await setDeliveryStatus(f.api,p,p.lines[0],'received');expect(f.db.get(ID)!.keywords).not.toContain('incoming');expect(JSON.parse(f.db.get(ID)!.attributes[await purchaseAttribute(p,p.lines[0].product)]).status).toBe('received');});
  it('keeps incoming tag if another order is still incoming',async()=>{const p=order(),f=fakeApi();await syncLine(f.api,p,p.lines[0],async()=>{});const other=order();other.key='other';other.orderId='222-2222222-2222222';await syncLine(f.api,other,other.lines[0],async()=>{});await setDeliveryStatus(f.api,p,p.lines[0],'received');expect(f.db.get(ID)!.keywords).toContain('incoming');});
  it('payload has all known API-required fields and links',()=>{const p=order();expect(createPayload(p,p.lines[0],'marker')).toMatchObject({storageType:'BULK',unit:{string:'units'},identifiers:[],idGenerators:[],defaultPrices:[],associatedLinks:[{label:'Amazon B012345678',link:'https://www.amazon.com/dp/B012345678'}]});});
  it('rejects multiplied quantities outside the supported range',()=>{const p=order();p.lines[0].mapping={productKey:'p',itemId:ID,itemName:'x',multiplier:1_000_000,unit:'units'};expect(()=>ledgerRecord(p,p.lines[0],'units')).toThrow();});
});
