
serial:
  # for demo
  port: /dev/ttyACM0
  baud: 115200
  extraPorts: "None"# list of extra port locations to consider
  preferredPaud: 115200
  

quarkus:
  http:
    port: 8080
    cors:
      ~: true
      origins: "*"

"%dev":
  quarkus:
    http:
      port: 8085