# Default values for oqm-core-api-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  core:
    api:
      image:
        tag: "1.1.4-dev"
      replicaCount: 1
      httpPort: 80
      httpsPort: 443
