package tech.ebp.oqm.core.api.model.object.storage.items.identifiers.generation;


import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.ToString;
import lombok.experimental.SuperBuilder;
import org.bson.types.ObjectId;
import org.eclipse.microprofile.openapi.annotations.media.Schema;
import tech.ebp.oqm.core.api.model.object.MainObject;
import tech.ebp.oqm.core.api.service.mongo.IdentifierGenerationService;

import java.math.BigInteger;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;


@EqualsAndHashCode(callSuper = true)
@Data
@ToString(callSuper = true)
@SuperBuilder(toBuilder = true)
@AllArgsConstructor
@NoArgsConstructor
public class IdentifierGenerator extends MainObject {
	public static final int CUR_SCHEMA_VERSION = 2;
	
	/**
	 * The name of the generator
	 */
	@NonNull
	@NotNull
	@lombok.Builder.Default
	@Schema(description = "The name of the generator.", examples = {"SKU"})
	private String name = null;
	
	/**
	 * The label to give resulting identifiers. Null to default to {@link #name}.
	 */
	@lombok.Builder.Default
	@Schema(description = "The label to give resulting identifiers. Null to default to the name.", examples = {"null", "sku"})
	private String label = null;
	
	public String getLabel(){
		if(this.label == null){
			return this.name;
		}
		return this.label;
	}
	
	/**
	 * What kind of objects this generator is intended for.
	 */
	@NonNull
	@NotNull
	@lombok.Builder.Default
	@Schema(description = "What kinds of objects this generator is intended for.")
	private LinkedHashSet<GeneratorFor> forObjectType = new LinkedHashSet<>();
	
	/**
	 * The format of the id. Details at {@link IdentifierGenerationService#getNextId(IdentifierGenerator)}
	 */
	@NotNull
	@NonNull
	@NotBlank
	@Schema(description = "The format of the identifiers generated by the generator.", examples = {"{rand}"})
	private String idFormat;
	
	/**
	 * The last generated increment
	 */
	@lombok.Builder.Default
	private BigInteger lastIncremented = null;
	
	/**
	 * If this generator uses an incrementor or not.
	 * @return
	 */
	@JsonProperty(access = JsonProperty.Access.READ_ONLY)
	public boolean hasIncrement(){
		return (this.lastIncremented != null);
	}
	
	/**
	 * If whether or not to base64 encode the resulting id string
	 */
	@lombok.Builder.Default
	@Schema(description = "If whether or not to base64 encode the resulting id string.", examples = {"false"})
	private boolean encoded = false;
	
	/**
	 * If the resulting ids are intended to be barcodes.
	 */
	@lombok.Builder.Default
	@Schema(description = "If the resulting ids are intended to be barcodes.", examples = {"false"})
	private boolean barcode = false;
	
	@Override
	public int getSchemaVersion() {
		return CUR_SCHEMA_VERSION;
	}
}
