package tech.ebp.oqm.core.api.model.rest.search;

import jakarta.ws.rs.QueryParam;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.bson.conversions.Bson;
import org.eclipse.microprofile.openapi.annotations.parameters.Parameter;
import tech.ebp.oqm.core.api.model.object.storage.items.identifiers.generation.GeneratorFor;
import tech.ebp.oqm.core.api.model.object.storage.items.identifiers.generation.IdentifierGenerator;
import tech.ebp.oqm.core.api.service.mongo.search.SearchUtils;

import java.util.List;

import static com.mongodb.client.model.Filters.eq;
import static com.mongodb.client.model.Filters.in;

@ToString(callSuper = true)
@Getter
@Setter
public class IdGeneratorSearch extends SearchObject<IdentifierGenerator> {
	
	@QueryParam("name")
	@Parameter(description = "The name of the generator to search for.")
	String name;
	
	@QueryParam("label")
	@Parameter(description = "The label the generator gives to resulting identifiers to search for.")
	String label;
	
	@QueryParam("generatorFor")
	@Parameter(description = "The type of object the generator is for.")
	GeneratorFor generatorFor;
	
	@QueryParam("format")
	@Parameter(description = "The format of the identifiers generated by the generator.")
	String format;
	
	@Override
	public List<Bson> getSearchFilters() {
		List<Bson> filters = super.getSearchFilters();
		
		if (hasValue(this.name)) {
			filters.add(SearchUtils.getBasicSearchFilter("name", this.name));
		}
		if (hasValue(this.label)) {
			filters.add(SearchUtils.getBasicSearchFilter("label", this.label));
		}
		if (hasValue(this.format)) {
			filters.add(SearchUtils.getBasicSearchFilter("format", this.format));
		}
		
		if(hasValue(this.generatorFor)){
			filters.add(in("forObjectType", this.generatorFor));
		}
		
		return filters;
	}
}
