apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      meta.helm.sh/release-name: mongodb
      meta.helm.sh/release-namespace: quartermaster
    generation: 1
    labels:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: mongodb
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: mongodb
      helm.sh/chart: mongodb-10.29.1
    name: mongodb
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/component: mongodb
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/name: mongodb
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: mongodb
          app.kubernetes.io/instance: mongodb
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: mongodb
          helm.sh/chart: mongodb-10.29.1
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: mongodb
                    app.kubernetes.io/instance: mongodb
                    app.kubernetes.io/name: mongodb
                namespaces:
                - quartermaster
                topologyKey: kubernetes.io/hostname
              weight: 1
        containers:
        - env:
          - name: BITNAMI_DEBUG
            value: "false"
          - name: MONGODB_ROOT_USER
            value: root
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mongodb-root-password
                name: mongodb
          - name: ALLOW_EMPTY_PASSWORD
            value: "no"
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
          - name: MONGODB_DISABLE_SYSTEM_LOG
            value: "no"
          - name: MONGODB_DISABLE_JAVASCRIPT
            value: "no"
          - name: MONGODB_ENABLE_JOURNAL
            value: "yes"
          - name: MONGODB_ENABLE_IPV6
            value: "no"
          - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            value: "no"
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - db.adminCommand('ping')
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: mongodb
          ports:
          - containerPort: 27017
            name: mongodb
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data/db
            name: datadir
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: mongodb
        serviceAccountName: mongodb
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: datadir
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "12"
    generation: 12
    labels:
      app: open-qm-base-station
      app.kubernetes.io/component: open-qm-base-station
      app.kubernetes.io/instance: open-qm-base-station
    name: open-qm-base-station
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        deployment: open-qm-base-station
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: open-qm-base-station
      spec:
        containers:
        - env:
          - name: quarkus.mongodb.connection-string
            value: mongodb://mongodb:27017
          - name: service.authMode
            value: EXTERNAL
          - name: mp.jwt.verify.publickey.location
            value: /tmp/keys/keycloak-public
          - name: mp.jwt.verify.issuer
            value: https://keycloak-sso.apps.sno-demo.nixon.com/auth/realms/apps
          - name: quarkus.oidc.authentication.scopes
            value: profile,address,email,address,phone,offline_access,microprofile-jwt
          - name: quarkus.rest-client.demoService.url
            value: http://open-qm-plugin-demo:8080
          - name: runningInfo.baseUrl
            value: https://quartermaster-quartermaster.apps.sno-demo.nixon.com/
          - name: service.externalAuth.url
            value: https://keycloak-sso.apps.sno-demo.nixon.com
          - name: service.externalAuth.realm
            value: apps
          - name: service.externalAuth.clientId
            value: quartermaster
          - name: service.externalAuth.clientSecret
            value: bfa4b025-e7d4-4fe0-9eb5-d9a5be644da4
          image: image-registry.openshift-image-registry.svc:5000/quartermaster/open-qm-base-station@sha256:3352b8ce8c3d0c327fa5970de03c2c384fe634562dca699aa2ddf37e769805b1
          imagePullPolicy: IfNotPresent
          name: open-qm-base-station
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          - containerPort: 9779
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp/keys/
            name: keycloak-public
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: keycloak-public
          secret:
            defaultMode: 420
            secretName: keycloak-public
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
    generation: 8
    labels:
      app: open-qm-plugin-demo
      app.kubernetes.io/component: open-qm-plugin-demo
      app.kubernetes.io/instance: open-qm-plugin-demo
    name: open-qm-plugin-demo
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        deployment: open-qm-plugin-demo
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: open-qm-plugin-demo
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/quartermaster/open-qm-plugin-demo:0.0.19-jvm
          imagePullPolicy: IfNotPresent
          name: open-qm-plugin-demo
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          - containerPort: 9779
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
