name: CI - Core - API

on:
  push:
    branches: [ "**" ]
    paths:
      - "software/core/oqm-core-api/**"
      - ".github/workflows/core-api.yml"
      - ".github/workflows/wf-quarkus-ci-pipeline.yml"
      - ".github/actions/setup-quarkus-runner/**"

  pull_request:
    branches: [ "**" ]
    paths:
      - "software/core/oqm-core-api/**"
      - ".github/workflows/core-api.yml"
      - ".github/workflows/wf-quarkus-ci-pipeline.yml"
      - ".github/actions/setup-quarkus-runner/**"

  workflow_call:
  workflow_dispatch:

concurrency:
  group: ci-core-api-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI-Pipeline:
    uses: ./.github/workflows/wf-quarkus-ci-pipeline.yml
    with:
      path: "software/core/oqm-core-api"
      java-version: "21"
      run-int-tests: true
      container-based-int-tests: false
