name: CI - Core - API

on:
  pull_request:
    paths:
      - "software/core/oqm-core-api/**"
      - ".github/workflows/core-api.yml"
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ci-core-api-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI-Pipeline:
    uses: Epic-Breakfast-Productions/ebp-ci/.github/workflows/quarkus-ci-pipeline.yml@main
    with:
      path: "software/core/oqm-core-api"
      java-version: "21"
      run-int-tests: true
      container-based-int-tests: true
