name: CI - Plugin - Storagotchi

on:
  pull_request:
    paths:
      - "software/plugins/storagotchi/**"
      - ".github/workflows/plugin-storagotchi.yml"
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ci-plugin-extItemSearch-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI-Pipeline:
    uses: Epic-Breakfast-Productions/ebp-ci/.github/workflows/quarkus-ci-pipeline.yml@main
    with:
      path: "software/plugins/storagotchi/"
      java-version: "25"
      run-int-tests: true
      container-based-int-tests: true
