name: CI - Plugin - External Item Search

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "**" ]
    paths:
      - "software/plugins/external-item-search/**"
      - ".github/workflows/plugin-extItemSearch.yml"
  pull_request:
    branches: [ "**" ]
    paths:
      - "software/plugins/external-item-search/**"
      - ".github/workflows/plugin-extItemSearch.yml"
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
defaults:
  run:
    working-directory: "software/plugins/external-item-search/"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    uses: ./.github/workflows/wf-gradleBuild.yaml
    with:
      path: "software/plugins/external-item-search/"
  unitTest:
    uses: ./.github/workflows/wf-gradleUnitTest.yaml
    with:
      path: "software/plugins/external-item-search/"
  intTest:
    uses: ./.github/workflows/wf-gradleQuarkusIntTest.yaml
    strategy:
      matrix:
        containerBased: [ false ] # TODO:: enable true
    with:
      path: "software/plugins/external-item-search/"
      containerBased: ${{ matrix.containerBased }}


