name: CI - Plugin - Image Search

on:
  pull_request:
    paths:
      - "software/plugins/image-search/**"
      - ".github/workflows/plugin-imageSearch.yml"
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ci-plugin-imageSearch-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI-Pipeline:
    uses: Epic-Breakfast-Productions/ebp-ci/.github/workflows/quarkus-ci-pipeline.yml@main
    with:
      path: "software/plugins/image-search/"
      java-version: "25"
      run-int-tests: true
      container-based-int-tests: false
