# This is a basic workflow to help you get started with Actions

name: CI - Manager - Station Captain

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "**" ]
    paths:
      - "software/Station-Captain/**"
      - ".github/workflows/stationCaptain.yml"
  pull_request:
    branches: [ "**" ]
    paths:
      - "software/Station-Captain/**"
      - ".github/workflows/stationCaptain.yml"
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
defaults:
  run:
    working-directory: "software/Station-Captain"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildTestUbuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Install dependencies
        run: sudo apt-get install -y dpkg-dev jq
      - name: Build with Maven
        run: ./mvnw verify
        working-directory: software/Station-Captain/stationCaptainTest
    
          # Runs a single command using the runners shell
      - name: Make Installers
        run: ./makeInstallers.sh
      - name: Archive Installers
        uses: actions/upload-artifact@v2
        with:
          name: Installers Produced
          path: "software/Station-Captain/bin"
      - name: Archive Cucumber Reports
        uses: actions/upload-artifact@v2
        with:
          name: Cucumber Test Reports
          path: "software/Station-Captain/stationCaptainTest/target/test-reports/*"
      - name: Cucumber Test Results to Annotation
        uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "software/Station-Captain/stationCaptainTest/target/test-reports/report.json"
