name: WF - Gradle Unit Test
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
jobs:
  unitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/wf-setup
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: ${{ inputs.path }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: Code Coverage Report
          path: "${{ inputs.path }}/build/jacoco-report"
      - name: Archive Unit Test Report
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Report
          path: "${{ inputs.path }}/build/reports/tests/test"
      # https://github.com/marketplace/actions/test-reporter
      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Unit Test Report            # Name of the check run which will be created
          path: "${{ inputs.path }}/build/test-results/test/*.xml"    # Path to test results
          reporter: java-junit        # Format of test results

